[package]
name = "llm-model-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = { version = "0.10.2", features = ["cuda"] }
candle-transformers = { version = "0.10.2", features = ["cuda"] }
tokenizers = "0.22.2"
clap = { version = "4.0", features = ["derive"] }
colored = "2.1"